---
  - hosts: default
    become: true

    tasks:
      - name: update the apt-get
        apt:
          update_cache: yes
      
      - name: Install apache2
        apt:
          name: "apache2"
          state: present

      - name: Create a directory if it does not exist
        file:
          path: "/var/www/green"
          state: directory

      - name: Copy my index page
        copy:
          src: "index.html"
          dest: "/var/www/green/index.html"

      - name: Copy configuration file for apache
        copy:
          src: "green.conf"
          dest: "/etc/apache2/sites-available/green.conf"

      - name: Enable site for green.conf
        command:
          a2ensite green.conf

      - name:
        command:
          a2dissite 000-default.conf

      - name: Restart apache2 server
        service:
          name: apache2
          state: restarted